#!/bin/sh

set -e

. "$(dirname "$0")/_/husky.sh"


yarn lint-staged --shell
yarn pretty-quick --staged


# For more information, see:
# https://github.com/typicode/husky/issues/912#issuecomment-939261395